---
name: docker compose basic validation
on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: false
        type: string

jobs:
  docker-compose-validate:
    runs-on: ${{ inputs.RUNS_ON || 'ubuntu-20.04' }}
    steps:
      - uses: actions/checkout@v4

      - name: validate config
        run: |
          docker compose config

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: validate pull
        run: |
          docker compose pull
