---
name: docker build and push
on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: false
        type: string

permissions:
  contents: read
  packages: write

jobs:
  docker-build:
    runs-on: ${{ inputs.RUNS_ON || 'ubuntu-20.04' }}
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker image
        run: |
          SHA="${{ github.sha }}"
          REF="${{ github.ref }}"
          REF_NAME="${REF##*/}"

          if [[ "$REF" == "refs/heads/main" ]]
          then
            export VERSION="latest"
          elif [[ "$REF" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]
          then
            export VERSION="$REF_NAME"
          else
            export VERSION="${SHA:0:7}"
          fi

          TAG="ghcr.io/${{ github.repository }}:$VERSION"
          echo "TAG=$TAG" >> "$GITHUB_ENV"
          export NETRC="${{ secrets.NETRC }}"

          docker build --build-arg=NETRC --build-arg=VERSION -t "$TAG" .

      - name: push docker image
        run: |
          docker push "$TAG"
