---
name: go linting
on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: false
        type: string
      GO_VERSION:
        required: false
        type: string

env:
  GO_VERSION: 1.20.10

jobs:
  golangci-lint:
    runs-on: ${{ inputs.RUNS_ON || 'ubuntu-20.04' }}
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.GO_VERSION || env.GO_VERSION }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --out-format=colored-line-number
