---
name: go static tests
on:
  workflow_call:
    inputs:
      RUNS_ON:
        required: false
        type: string
      GO_VERSION:
        required: false
        type: string
      GO_TEST_ARGS:
        required: false
        type: string

env:
  GO_VERSION: 1.20.10

jobs:
  # https://github.com/golang/govulncheck-action
  govulncheck:
    runs-on: ${{ inputs.RUNS_ON || 'ubuntu-20.04' }}
    steps:
      - uses: actions/checkout@v4
      - name: setup netrc
        run: |
          echo ${{ secrets.NETRC }} > ~/.netrc
          chmod 600 ~/.netrc
          go env -w GOPRIVATE="github.com/${{ github.repository_owner }}/*"
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.GO_VERSION || env.GO_VERSION }}
      - name: setup govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@v1.0.1
      - name: govulncheck
        run: |
          govulncheck -C . ${{ inputs.GO_TEST_ARGS }} ./...

  # https://github.com/sonatype-nexus-community/nancy-github-action
  sonatype:
    runs-on: ${{ inputs.RUNS_ON || 'ubuntu-20.04' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.GO_VERSION || env.GO_VERSION }}
      - run: go list ${{ inputs.GO_TEST_ARGS }} -json -deps ./... > go.list
      - uses: sonatype-nexus-community/nancy-github-action@v1.0.3
