name: yamllint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-workflows:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.github/workflows'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
